export default {
    FETCH_SHIMPENTS_SUMMARY_START: 'FETCH_SHIMPENTS_SUMMARY_START',
    FETCH_SHIMPENTS_SUMMARY_SUCCESS: 'FETCH_SHIMPENTS_SUMMARY_SUCCESS',
    FETCH_SHIMPENTS_SUMMARY_FAILURE: 'FETCH_SHIMPENTS_SUMMARY_FAILURE',
    FETCH_SHIPMENTS_FOR_EVENT_START: 'FETCH_SHIPMENTS_FOR_EVENT_START',
    FETCH_SHIPMENTS_FOR_EVENT_SUCCESS: 'FETCH_SHIPMENTS_FOR_EVENT_SUCCESS',
    FETCH_SHIPMENTS_FOR_EVENT_FAILURE: 'FETCH_SHIPMENTS_FOR_EVENT_FAILURE',
    FETCH_SHIPMENT_DETAILS_START: 'FETCH_SHIPMENT_DETAILS_START',
    FETCH_SHIPMENT_DETAILS_SUCCESS: 'FETCH_SHIPMENT_DETAILS_SUCCESS',
    FETCH_SHIPMENT_DETAILS_FAILURE: 'FETCH_SHIPMENT_DETAILS_FAILURE',
    SHIPMENT_EVENT_CLICKED: 'SHIPMENT_EVENT_CLICKED'
};