export default {
    LOGIN_START: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    GET_AUTH_DATA: 'GET_AUTH_DATA',
    SET_AUTH_DATA: 'SET_AUTH_DATA',
    INITIALIZE_AUTH_DATA: 'INITIALIZE_AUTH_DATA',
    LOGOUT_START: 'LOGOUT_START',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
};